dist: xenial
language: python
jobs:
  include:
    - python: "2.7"
      env: PARAMIKO_VER=2.5.0
    - python: "3.4"
      env: PARAMIKO_VER=2.5.0
    - python: "3.5"
      env: PARAMIKO_VER=2.5.0
    - python: "3.6"
      env: PARAMIKO_VER=2.5.0
    - python: "2.7"
      env: PARAMIKO_VER=2.7.6
    - python: "3.4"
      env: PARAMIKO_VER=2.7.6
    - python: "3.7"
      env: PARAMIKO_VER=2.7.6 BUILD_DOCS=true
    - python: "3.8"
      env: PARAMIKO_VER=2.7.6

install:
  # Build/test dependencies
  - pip install -r dev-requirements.txt
  # docs site dependencies
  - if [ -n "$BUILD_DOCS" ]; then
        pip install -r doc-requirements.txt;
    fi
  # install fab to test fab
  - pip install paramiko-ng==$PARAMIKO_VER
  - pip install -e .
before_script:
  # Allow us to SSH passwordless to localhost
  - echo "export TRAVIS_HOME=$TRAVIS_HOME" | cat - ~/.bashrc > ~/.bashrc.mod
  - mv -v ~/.bashrc.mod ~/.bashrc
  - ssh-keygen -f ~/.ssh/id_rsa -N ""
  - cp ~/.ssh/{id_rsa.pub,authorized_keys}
  # Creation of an SSH agent for testing forwarding
  - eval $(ssh-agent)
  - ssh-add
script:
  - flake8
  # Normal tests
  - fab test
  # Integration tests
  - fab -H localhost test:integration
  # test docs build
  - if [ -n "$BUILD_DOCS" ]; then
        sphinx-build -W sites/docs tmpbuild;
    fi
branches:
  only:
  - master
notifications:
  email: false
