dist: xenial
language: python
python:
  - "2.7"
  - "3.4"
  - "3.6"
  - "3.7"
install:
  # Build/test dependencies
  - pip install -r dev-requirements.txt
  # install fab to test fab
  - pip install -e .
before_script:
  # Allow us to SSH passwordless to localhost
  - ssh-keygen -f ~/.ssh/id_rsa -N ""
  - cp ~/.ssh/{id_rsa.pub,authorized_keys}
  # Creation of an SSH agent for testing forwarding
  - eval $(ssh-agent)
  - ssh-add
script:
  - flake8
  # Normal tests
  - fab test
  # Integration tests
  - fab -H localhost test:integration
branches:
  only:
  - master
notifications:
  email: false
